services:
  - type: web
    name: syd-api
    env: node
    region: brazil # ou escolha outra região mais próxima
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GODADDY_EMAIL
        sync: false # será configurado manualmente no dashboard
      - key: GODADDY_PASS
        sync: false # será configurado manualmente no dashboard
